
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author IT
 */
public class main_page extends javax.swing.JFrame {
int season_id=0;
    /**
     * Creates new form main_page
     */
    public main_page() {
        initComponents();
        
       Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screensize.width, screensize.height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_menu = new javax.swing.JPanel();
        menu_purchase = new javax.swing.JButton();
        menu_lifting = new javax.swing.JButton();
        menu_rec_bardana = new javax.swing.JButton();
        menu_issue_bardana = new javax.swing.JButton();
        menu_firm_reports = new javax.swing.JButton();
        menu_pg_reports = new javax.swing.JButton();
        menu_consolidated = new javax.swing.JButton();
        menu_shortage = new javax.swing.JButton();
        menu_change_mandi = new javax.swing.JButton();
        menu_admin = new javax.swing.JButton();
        menu_update = new javax.swing.JButton();
        panel_total_detail = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        txt_total_purchase = new javax.swing.JTextField();
        txt_total_lift = new javax.swing.JTextField();
        txt_total_balance = new javax.swing.JTextField();
        txt_total_bardana = new javax.swing.JTextField();
        txt_total_bar_balance = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_main_empty = new javax.swing.JPanel();
        panel_empty = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_menu.setBackground(new java.awt.Color(0, 0, 0));
        panel_menu.setMinimumSize(new java.awt.Dimension(1100, 33));
        panel_menu.setPreferredSize(new java.awt.Dimension(1200, 30));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        panel_menu.setLayout(flowLayout1);

        menu_purchase.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_purchase.setText("Purchase");
        menu_purchase.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_purchase.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_purchaseActionPerformed(evt);
            }
        });
        panel_menu.add(menu_purchase);

        menu_lifting.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_lifting.setText("Lifting");
        menu_lifting.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_lifting.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_lifting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_liftingActionPerformed(evt);
            }
        });
        panel_menu.add(menu_lifting);

        menu_rec_bardana.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_rec_bardana.setText("Rec Bardana");
        menu_rec_bardana.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_rec_bardana.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_rec_bardana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rec_bardanaActionPerformed(evt);
            }
        });
        panel_menu.add(menu_rec_bardana);

        menu_issue_bardana.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_issue_bardana.setText("Issue Bardana");
        menu_issue_bardana.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_issue_bardana.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_issue_bardana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_issue_bardanaActionPerformed(evt);
            }
        });
        panel_menu.add(menu_issue_bardana);

        menu_firm_reports.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_firm_reports.setText("Firm Reports");
        menu_firm_reports.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_firm_reports.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_firm_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_firm_reportsActionPerformed(evt);
            }
        });
        panel_menu.add(menu_firm_reports);

        menu_pg_reports.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_pg_reports.setText("PG Reports");
        menu_pg_reports.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_pg_reports.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_pg_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pg_reportsActionPerformed(evt);
            }
        });
        panel_menu.add(menu_pg_reports);

        menu_consolidated.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_consolidated.setText("Consolidated");
        menu_consolidated.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_consolidated.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_consolidated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consolidatedActionPerformed(evt);
            }
        });
        panel_menu.add(menu_consolidated);

        menu_shortage.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_shortage.setText("Shortage");
        menu_shortage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_shortage.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_shortage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_shortageActionPerformed(evt);
            }
        });
        panel_menu.add(menu_shortage);

        menu_change_mandi.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_change_mandi.setText("Change Mandi");
        menu_change_mandi.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_change_mandi.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_change_mandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_change_mandiActionPerformed(evt);
            }
        });
        panel_menu.add(menu_change_mandi);

        menu_admin.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_admin.setText("Admin");
        menu_admin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_admin.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_adminActionPerformed(evt);
            }
        });
        panel_menu.add(menu_admin);

        menu_update.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        menu_update.setText("Update/Delete");
        menu_update.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menu_update.setPreferredSize(new java.awt.Dimension(90, 20));
        menu_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateActionPerformed(evt);
            }
        });
        panel_menu.add(menu_update);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(panel_menu, gridBagConstraints);

        panel_total_detail.setBackground(new java.awt.Color(51, 102, 0));
        panel_total_detail.setAlignmentY(0.0F);
        panel_total_detail.setMinimumSize(new java.awt.Dimension(1200, 60));
        panel_total_detail.setPreferredSize(new java.awt.Dimension(1250, 60));
        panel_total_detail.setLayout(new java.awt.GridBagLayout());

        jPanel48.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        panel_total_detail.add(jPanel48, gridBagConstraints);

        txt_total_purchase.setEditable(false);
        txt_total_purchase.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_total_purchase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_total_purchase.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        panel_total_detail.add(txt_total_purchase, gridBagConstraints);

        txt_total_lift.setEditable(false);
        txt_total_lift.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_total_lift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_total_lift.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel_total_detail.add(txt_total_lift, gridBagConstraints);

        txt_total_balance.setEditable(false);
        txt_total_balance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_total_balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_total_balance.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        panel_total_detail.add(txt_total_balance, gridBagConstraints);

        txt_total_bardana.setEditable(false);
        txt_total_bardana.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_total_bardana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_total_bardana.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        panel_total_detail.add(txt_total_bardana, gridBagConstraints);

        txt_total_bar_balance.setEditable(false);
        txt_total_bar_balance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_total_bar_balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_total_bar_balance.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        panel_total_detail.add(txt_total_bar_balance, gridBagConstraints);

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("TOTAL PURCHASE");
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel58.setMinimumSize(new java.awt.Dimension(150, 25));
        jLabel58.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_total_detail.add(jLabel58, gridBagConstraints);

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("BALANCE WHEAT");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel59.setMinimumSize(new java.awt.Dimension(150, 25));
        jLabel59.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panel_total_detail.add(jLabel59, gridBagConstraints);

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("BALANCE BARDANA");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel60.setMinimumSize(new java.awt.Dimension(150, 25));
        jLabel60.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        panel_total_detail.add(jLabel60, gridBagConstraints);

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("TOTAL LIFT");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel61.setMinimumSize(new java.awt.Dimension(150, 25));
        jLabel61.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panel_total_detail.add(jLabel61, gridBagConstraints);

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("BARDANA RECIEVED");
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel62.setMinimumSize(new java.awt.Dimension(150, 25));
        jLabel62.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        panel_total_detail.add(jLabel62, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(panel_total_detail, gridBagConstraints);

        panel_main.setLayout(new java.awt.GridBagLayout());

        panel_main_empty.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panel_emptyLayout = new javax.swing.GroupLayout(panel_empty);
        panel_empty.setLayout(panel_emptyLayout);
        panel_emptyLayout.setHorizontalGroup(
            panel_emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_emptyLayout.setVerticalGroup(
            panel_emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_main_empty.add(panel_empty, "card8");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel_main.add(panel_main_empty, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(panel_main, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_purchaseActionPerformed
/*
        CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "data_entry");

        // panel_main.setVisible(true);
        lbl_entry_header.setText("NEW PURCHASE");
        visibility_purchase();
        //    load_aarthia();
        load_bardana_recieved();
        selection = 1;
        data_entry_view obj = new data_entry_view();
        TableModel model = obj.view_purchase(season_id);
        table_data_entry.setModel(model);

        //   table_bardana_purchase();
        //   DefaultTableModel tb = (DefaultTableModel) table_consolidate.getModel();
        //  tb.setColumnCount(0);
        //   table_purchase();
        // TODO add your handling code here:*/
    }//GEN-LAST:event_menu_purchaseActionPerformed

    private void menu_liftingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_liftingActionPerformed
/*
        CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "data_entry");
        lbl_entry_header.setText("NEW LIFTING");
        visibility_lifting();
        selection = 2;
        data_entry_view obj = new data_entry_view();
        TableModel model = obj.view_lifting(season_id);
        table_data_entry.setModel(model);
        load_godown();

        //  load_bardana_purchased();
        //  table_bardana_purchase();
        //   table_lifting();
        //   DefaultTableModel tb = (DefaultTableModel) table_consolidate.getModel();
        // tb.setColumnCount(0);*/
    }//GEN-LAST:event_menu_liftingActionPerformed

    private void menu_rec_bardanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rec_bardanaActionPerformed
    /*    CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "data_entry");
        visibility_bardana_rec();
        lbl_entry_header.setText("NEW BARDANA REC");
        load_bardana();
        selection = 3;
        data_entry_view obj = new data_entry_view();
        TableModel model = obj.view_bardana_recieve(season_id);
        table_data_entry.setModel(model);*/
    }//GEN-LAST:event_menu_rec_bardanaActionPerformed

    private void menu_issue_bardanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_issue_bardanaActionPerformed
/*
        CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "data_entry");

        //        panel_data_entries.setVisible(true);
        lbl_entry_header.setText("NEW BARDANA ISSUE");
        visibility_bardana_issue();
        selection = 4;
        //     load_aarthia();
        load_bardana_recieved();
        data_entry_view obj = new data_entry_view();
        TableModel model = obj.view_bardana_issue(season_id);
        table_data_entry.setModel(model);

        //   table_bardana_purchase();    */    // TODO add your handling code here:
    }//GEN-LAST:event_menu_issue_bardanaActionPerformed

    private void menu_firm_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_firm_reportsActionPerformed
    /*    CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "firm_reports");

        //    cb_report_bardana.setEnabled(false);
        //   cb_report_godown.setEnabled(false);
        //   btn_firmwise_purchase.setVisible(false);
        //   btn_firm_lifting.setVisible(false);
        //  btn_firm_bardana.setVisible(false);
        //  btn_firm_pdf.setEnabled(false);
        //     dialog_firm.setSize(screensize.width, screensize.height);
        //  dialog_firm.setLocationRelativeTo(panel_main);
        //   dialog_firm.setVisible(true);
        // dialog_firm.// TODO add your handling code here:*/
    }//GEN-LAST:event_menu_firm_reportsActionPerformed

    private void menu_pg_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pg_reportsActionPerformed
    /*    CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "pg_reports");

        //        dialog_pg4.setSize(800, 800);
        //      dialog_pg4.setLocationRelativeTo(null);
        //     dialog_pg4.setVisible(true);
        //  cb_pg.removeAllItems();
        //   stock_report obj = new stock_report();
        //  ResultSet rs = obj.filling(season_id);
        /*  try {
            while (rs.next()) {
                cb_pg.addItem(rs.getString(1));
            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(main_page.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_menu_pg_reportsActionPerformed

    private void menu_consolidatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consolidatedActionPerformed
    /*    CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "consolidated");*/

    }//GEN-LAST:event_menu_consolidatedActionPerformed

    private void menu_shortageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_shortageActionPerformed
  /*      CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "shortage");
        try {
            Connection conn = connectdb.getConn();
            String query = "select sum(purchase.bags),sum(purchase.weight),sum(lifting.bags),sum(lifting.weight) from purchase left join lifting on purchase.season_id=lifting.season_id where purchase.season_id=?";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setInt(1, season_id);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                total_purchase_bags = rs.getInt(1);
                total_purchase_qtl = rs.getFloat(2);
                total_lift_bags = rs.getInt(3);
                total_lift_qtl = rs.getFloat(4);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        txt_total_purchase.setText(String.valueOf(total_purchase_bags + "  Bags   " + total_purchase_qtl + " Qtl"));
        txt_total_lift.setText(String.valueOf(total_lift_bags + "  Bags   " + total_lift_qtl + " Qtl"));
*/
    }//GEN-LAST:event_menu_shortageActionPerformed

    private void menu_change_mandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_change_mandiActionPerformed

        select_mandi obj = new select_mandi();
        this.setVisible(false);
        this.dispose();
        obj.setSize(400, 300);
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);

    }//GEN-LAST:event_menu_change_mandiActionPerformed

    private void menu_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_adminActionPerformed
/*
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        txt1.setVisible(false);
        txt2.setVisible(false);
        txt3.setVisible(false);
        txt4.setVisible(false);
        ad_btn_add.setVisible(false);
        ad_btn_cancel.setVisible(false);
        lbl_admin_header.setText("ADD NEW ITEM");

        admin.setSize(682, 435);
        admin.setLocationRelativeTo(null);
        //  obj.setVisible(true);
        admin.setVisible(true);

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menu_adminActionPerformed

    private void menu_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateActionPerformed
  /*      CardLayout card = (CardLayout) panel_main_empty.getLayout();
        card.show(panel_main_empty, "update");

        //  dialog_modify.setSize(800, 800);
        //  dialog_modify.setLocationRelativeTo(null);
        //  dialog_modify.setVisible(true);
        //  modify_panel.setVisible(false);
        // TODO add your handling code here:*/
    }//GEN-LAST:event_menu_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JButton menu_admin;
    private javax.swing.JButton menu_change_mandi;
    private javax.swing.JButton menu_consolidated;
    private javax.swing.JButton menu_firm_reports;
    private javax.swing.JButton menu_issue_bardana;
    private javax.swing.JButton menu_lifting;
    private javax.swing.JButton menu_pg_reports;
    private javax.swing.JButton menu_purchase;
    private javax.swing.JButton menu_rec_bardana;
    private javax.swing.JButton menu_shortage;
    private javax.swing.JButton menu_update;
    private javax.swing.JPanel panel_empty;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_main_empty;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_total_detail;
    public javax.swing.JTextField txt_total_balance;
    public javax.swing.JTextField txt_total_bar_balance;
    public javax.swing.JTextField txt_total_bardana;
    public javax.swing.JTextField txt_total_lift;
    public javax.swing.JTextField txt_total_purchase;
    // End of variables declaration//GEN-END:variables
}
