
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gulshankumar
 */
public class select_mandi extends javax.swing.JFrame {

    int total_purchase_bags = 0;
    float total_purchase_weight = 0;
    int total_lift_bags = 0;
    float total_lift_weight = 0;
    int total_bales = 0;
    int total_loose = 0;
    int balance_wheat_bags = 0;
    float balance_wheat_qtl = 0;
    int balance_bardana = 0;

    //  String url = "jdbc:sqlite:/Users/gulshankumar/Documents/SOFTWARE/mandi.db";
    //  int season_id = 0;
    /**
     * Creates new form test_form
     */
    public select_mandi() {
        initComponents();
        load_crop_year();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        new_season = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cb_crop_year = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cb_mandi = new javax.swing.JComboBox<>();
        cb_crop_type = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        new_season.setModal(true);
        new_season.setUndecorated(true);

        jLabel8.setText("Add New Season");

        jLabel9.setText("Crop Year");

        jLabel10.setText("Mandi");

        jLabel11.setText("Crop Type");

        jButton6.setText("Add ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton6)
                                .addGap(26, 26, 26)
                                .addComponent(jButton7))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(151, 151, 151)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(txt2))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        new_season.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("SELECT MANDI");
        jPanel29.add(jLabel20);

        jPanel1.add(jPanel29, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        cb_crop_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLEASE SELECT" }));
        cb_crop_year.setPreferredSize(new java.awt.Dimension(180, 25));
        cb_crop_year.setRequestFocusEnabled(false);
        cb_crop_year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_crop_yearItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel10.add(cb_crop_year, gridBagConstraints);

        jButton5.setText("Add New Season");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanel10.add(jButton5, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("CROP YEAR");
        jLabel31.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 0, 15);
        jPanel10.add(jLabel31, gridBagConstraints);

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("CROP TYPE");
        jLabel52.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 0, 15);
        jPanel10.add(jLabel52, gridBagConstraints);

        cb_mandi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLEASE SELECT" }));
        cb_mandi.setPreferredSize(new java.awt.Dimension(150, 25));
        cb_mandi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mandiItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel10.add(cb_mandi, gridBagConstraints);

        cb_crop_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLEASE SELECT" }));
        cb_crop_type.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel10.add(cb_crop_type, gridBagConstraints);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("MANDI");
        jLabel51.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 0, 15);
        jPanel10.add(jLabel51, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel10.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton9.setText("SUBMIT");
        jButton9.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 15);
        jPanel3.add(jButton9, gridBagConstraints);

        jButton10.setText("CLOSE");
        jButton10.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel3.add(jButton10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 70, 0, 0);
        jPanel10.add(jPanel3, gridBagConstraints);

        jPanel1.add(jPanel10, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_crop_yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_crop_yearItemStateChanged

        load_mandi();


    }//GEN-LAST:event_cb_crop_yearItemStateChanged

    private void cb_mandiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mandiItemStateChanged
        load_crop_type();

        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mandiItemStateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (cb_crop_year.getSelectedItem().toString().equals("Please Select")
                || cb_mandi.getSelectedItem().toString().equals("Please Select")
                || cb_crop_type.getSelectedItem().toString().equals("Please Select")) {
            JOptionPane.showMessageDialog(null, "Please Select All Options");
        } else {
            int s_id = 0;
            s_id = load_season_id();
            if (s_id > 0) {
                main_page obj = new main_page();
                obj.season_id = s_id;
                obj.setTitle("CROP YEAR: " + cb_crop_year.getSelectedItem().toString() + "          " + "MANDI:  "
                        + cb_mandi.getSelectedItem().toString() + "          " + "TYPE:  " + cb_crop_type.getSelectedItem().toString());
                obj.total_report();
                obj.table_firms();
                obj.table_bardana();
                obj.table_godown();
//    obj.load_aarthia();
                this.setVisible(false);
                this.dispose();
                obj.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please Check Your Record Again");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

     new_season.setSize(500, 500);
       new_season.setLocationRelativeTo(null);
        new_season.setVisible(true);

       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(txt1.getText().equals("")||
     txt2.getText().equals("")||
        txt3.getText().equals(""))
{
    JOptionPane.showMessageDialog(null, "Please Fill All The Options.");
}
else
{
    

        try {
            Connection conn = connectdb.getConn();
            String query = "insert into season (crop_year,mandi,crop_type) values(?,?,?) ";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, txt1.getText());
            statement.setString(2, txt2.getText());
            statement.setString(3, txt3.getText());
            int i = statement.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "RECORD ADDED");
                txt1.setText("");
                txt2.setText("");
                txt3.setText("");
                load_crop_year();
            } else {
                JOptionPane.showMessageDialog(null, "CAN NOT ADD RECORD ");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE OPTIONS");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
new_season.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_mandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_mandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_mandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_mandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_mandi().setVisible(true);
            }
        });
    }

    public void load_crop_year() {
        //    conn=null;
        cb_crop_year.removeAllItems();
        cb_crop_year.addItem("Please Select");
        try {
            Connection conn = connectdb.getConn();
            String query = "select distinct crop_year  from season order by  crop_year DESC ";
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                cb_crop_year.addItem(result.getString("crop_year"));
            }
            //    conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "  crop");
        }

    } // load crop year to cb

    public void load_mandi() {

        try {
            Connection conn = connectdb.getConn();
            cb_mandi.removeAllItems();
            cb_mandi.addItem("Please Select");
            String query = "select distinct mandi  from season where crop_year=? order by  mandi ASC ";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, cb_crop_year.getSelectedItem().toString());
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                cb_mandi.addItem(result.getString("mandi"));
            }
            //    conn.close();
        } catch (Exception e) {
            //    JOptionPane.showMessageDialog(null,e+"  mandi");
        }

    } // load mandi to cb

    public void load_crop_type() {
        try {
            Connection conn = connectdb.getConn();
            cb_crop_type.removeAllItems();
            cb_crop_type.addItem("Please Select");
            String query = "select  crop_type  from season where crop_year=? and mandi=?  ";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, cb_crop_year.getSelectedItem().toString());
            statement.setString(2, cb_mandi.getSelectedItem().toString());
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                cb_crop_type.addItem(result.getString(1));

            }
            //    conn.close();
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null,e);
        }
    } // load data

    public int load_season_id() {
        int id = 0;
        try {
            Connection conn = connectdb.getConn();
            String query = "select season_id from season where crop_year=? and mandi=? and crop_type=? ";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, cb_crop_year.getSelectedItem().toString());
            statement.setString(2, cb_mandi.getSelectedItem().toString());
            statement.setString(3, cb_crop_type.getSelectedItem().toString());
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                id = result.getInt("season_id");
            }
            //   conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error on season_id " + e);
        }
        return id;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_crop_type;
    private javax.swing.JComboBox<String> cb_crop_year;
    private javax.swing.JComboBox<String> cb_mandi;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JDialog new_season;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
